import Image from 'next/image'
import frontPageLogo from '../public/SquareLogo.png'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center p-6 overflow-x-hidden">
      <Image 
        src={frontPageLogo} 
        alt='Logo for Many Sided Media Company' 
        className='lg:w-5/12 animate-bounceFP' 
      />
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>
      <p className='my-8'>
        [INSERT TEXT HERE ABOUT MANY SIDED MEDIA EXPLAINING WHAT IT IS AND WHAT YOU PROVIDE AND ANYTHING ELSE YOU THINK WOULD BELONG HERE]
      </p>

    </main>
  )
}
